from videomind.config import get_settings
s = get_settings()
print('APP_NAME:', s.app_name)
print('ENV:', s.env)
print('DATABASE_URL:', s.database_url[:50] + '...')
print('REDIS_URL:', s.redis_url)
print('QDRANT_URL:', s.qdrant_url)
print('MINIO_ENDPOINT:', s.minio_endpoint)
print('ASR_PROVIDER:', s.asr_provider)
print('OCR_PROVIDER:', s.ocr_provider)
print('EMBEDDING_PROVIDER:', s.embedding_provider)
print('CELERY_BROKER_URL:', s.celery_broker_url)
print('GPU_LOCK_TTL:', s.gpu_lock_ttl)
print('All settings loaded OK')