"""make user_id nullable in media_file

Revision ID: ac2c0859ceb3
Revises: 53ce57071856
Create Date: 2026-07-24 19:26:30.241243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2c0859ceb3'
down_revision: Union[str, None] = '53ce57071856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_file', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('media_file_user_id_fkey', 'media_file', type_='foreignkey')
    op.create_foreign_key(None, 'media_file', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_file', type_='foreignkey')
    op.create_foreign_key('media_file_user_id_fkey', 'media_file', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('media_file', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###