"""initial

Revision ID: bf08b9489483
Revises: 
Create Date: 2026-07-24 18:38:40.337418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf08b9489483'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('celery_id', sa.String(length=64), nullable=False),
    sa.Column('args_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kwargs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=64), nullable=True),
    sa.Column('worker_hostname', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_id')
    )
    op.create_index(op.f('ix_celery_task_status'), 'celery_task', ['status'], unique=False)
    op.create_index(op.f('ix_celery_task_task_name'), 'celery_task', ['task_name'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('real_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('api_key',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_suffix', sa.String(length=4), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_whitelist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=False)
    op.create_index('ux_api_key_prefix', 'api_key', ['key_prefix'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_user_id'), 'knowledge_base', ['user_id'], unique=False)
    op.create_table('media_file',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('minio_bucket', sa.String(length=64), nullable=False),
    sa.Column('minio_object', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_object', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_media_file_status'), 'media_file', ['status'], unique=False)
    op.create_index(op.f('ix_media_file_user_id'), 'media_file', ['user_id'], unique=False)
    op.create_index('ix_media_source_url', 'media_file', ['source_url'], unique=False, postgresql_where=sa.text('source_url IS NOT NULL'))
    op.create_table('membership',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('monthly_token_quota', sa.BigInteger(), nullable=False),
    sa.Column('monthly_token_used', sa.BigInteger(), nullable=False),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('user_ai_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('api_key_encrypted', postgresql.BYTEA(), nullable=True),
    sa.Column('api_key_nonce', postgresql.BYTEA(), nullable=True),
    sa.Column('api_base_url', sa.String(length=512), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_provider', sa.String(length=32), nullable=True),
    sa.Column('asr_model', sa.String(length=64), nullable=True),
    sa.Column('ocr_model', sa.String(length=64), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'model_name', name='uq_uac_provider_model')
    )
    op.create_index(op.f('ix_user_ai_config_user_id'), 'user_ai_config', ['user_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_ur_role', 'user_role', ['role_id'], unique=False)
    op.create_table('ai_call_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acl_created', 'ai_call_logs', ['created_at'], unique=False)
    op.create_index('ix_acl_provider_model', 'ai_call_logs', ['provider', 'model', 'created_at'], unique=False)
    op.create_index('ix_acl_user_time', 'ai_call_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('analysis_task',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('goal_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('final_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'goal_hash', name='uq_at_media_goal')
    )
    op.create_index(op.f('ix_analysis_task_media_id'), 'analysis_task', ['media_id'], unique=False)
    op.create_index(op.f('ix_analysis_task_status'), 'analysis_task', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_task_user_id'), 'analysis_task', ['user_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('minio_object', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_kb_id'), 'document', ['kb_id'], unique=False)
    op.create_index(op.f('ix_document_user_id'), 'document', ['user_id'], unique=False)
    op.create_table('frame_ocr',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('frame_ms', sa.BigInteger(), nullable=False),
    sa.Column('minio_object', sa.String(length=512), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('phash', sa.String(length=16), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'frame_ms', name='uq_fo_media_frame')
    )
    op.create_index('ix_fo_phash', 'frame_ocr', ['phash'], unique=False, postgresql_where=sa.text('phash IS NOT NULL'))
    op.create_index(op.f('ix_frame_ocr_media_id'), 'frame_ocr', ['media_id'], unique=False)
    op.create_table('ingestion_task',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('celery_task_id', sa.UUID(), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['celery_task_id'], ['celery_task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'stage', name='uq_it_media_stage')
    )
    op.create_index(op.f('ix_ingestion_task_media_id'), 'ingestion_task', ['media_id'], unique=False)
    op.create_index(op.f('ix_ingestion_task_status'), 'ingestion_task', ['status'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_media_id'), 'session', ['media_id'], unique=False)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('transcription',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', name='uq_tr_media')
    )
    op.create_index(op.f('ix_transcription_media_id'), 'transcription', ['media_id'], unique=False)
    op.create_table('transcription_chunk',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('audio_object', sa.String(length=512), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'chunk_index', name='uq_tc_media_index')
    )
    op.create_index(op.f('ix_transcription_chunk_media_id'), 'transcription_chunk', ['media_id'], unique=False)
    op.create_index(op.f('ix_transcription_chunk_status'), 'transcription_chunk', ['status'], unique=False)
    op.create_table('video_segment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ocr_texts', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('evidence_frames', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'segment_index', name='uq_vs_media_index')
    )
    op.create_index(op.f('ix_video_segment_media_id'), 'video_segment', ['media_id'], unique=False)
    op.create_index('ix_vs_time', 'video_segment', ['media_id', 'start_ms'], unique=False)
    op.create_table('agent_checkpoint',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('agent_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('video_context_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('critique_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('required_timestamps', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'round', 'phase', name='uq_acp_task_round_phase')
    )
    op.create_index(op.f('ix_agent_checkpoint_task_id'), 'agent_checkpoint', ['task_id'], unique=False)
    op.create_table('agent_result',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('conclusions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggestions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('critic_passed', sa.Boolean(), nullable=False),
    sa.Column('critic_feedback', sa.Text(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_result_task_id'), 'agent_result', ['task_id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=True),
    sa.Column('end_ms', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('qdrant_point_id', sa.UUID(), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['video_segment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'chunk_index', name='uq_chunk_media_index')
    )
    op.create_index(op.f('ix_chunk_content_hash'), 'chunk', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chunk_media_id'), 'chunk', ['media_id'], unique=False)
    op.create_index('ix_chunk_qdrant_id', 'chunk', ['qdrant_point_id'], unique=False, postgresql_where=sa.text('qdrant_point_id IS NOT NULL'))
    op.create_table('rag_trace',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('rewritten_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intent_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fused_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expanded_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reranked_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_trace_created_at'), 'rag_trace', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_trace_task_id'), 'rag_trace', ['task_id'], unique=False)
    op.create_index(op.f('ix_rag_trace_user_id'), 'rag_trace', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_trace_user_id'), table_name='rag_trace')
    op.drop_index(op.f('ix_rag_trace_task_id'), table_name='rag_trace')
    op.drop_index(op.f('ix_rag_trace_created_at'), table_name='rag_trace')
    op.drop_table('rag_trace')
    op.drop_index('ix_chunk_qdrant_id', table_name='chunk', postgresql_where=sa.text('qdrant_point_id IS NOT NULL'))
    op.drop_index(op.f('ix_chunk_media_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_content_hash'), table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_agent_result_task_id'), table_name='agent_result')
    op.drop_table('agent_result')
    op.drop_index(op.f('ix_agent_checkpoint_task_id'), table_name='agent_checkpoint')
    op.drop_table('agent_checkpoint')
    op.drop_index('ix_vs_time', table_name='video_segment')
    op.drop_index(op.f('ix_video_segment_media_id'), table_name='video_segment')
    op.drop_table('video_segment')
    op.drop_index(op.f('ix_transcription_chunk_status'), table_name='transcription_chunk')
    op.drop_index(op.f('ix_transcription_chunk_media_id'), table_name='transcription_chunk')
    op.drop_table('transcription_chunk')
    op.drop_index(op.f('ix_transcription_media_id'), table_name='transcription')
    op.drop_table('transcription')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_media_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_ingestion_task_status'), table_name='ingestion_task')
    op.drop_index(op.f('ix_ingestion_task_media_id'), table_name='ingestion_task')
    op.drop_table('ingestion_task')
    op.drop_index(op.f('ix_frame_ocr_media_id'), table_name='frame_ocr')
    op.drop_index('ix_fo_phash', table_name='frame_ocr', postgresql_where=sa.text('phash IS NOT NULL'))
    op.drop_table('frame_ocr')
    op.drop_index(op.f('ix_document_user_id'), table_name='document')
    op.drop_index(op.f('ix_document_kb_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_analysis_task_user_id'), table_name='analysis_task')
    op.drop_index(op.f('ix_analysis_task_status'), table_name='analysis_task')
    op.drop_index(op.f('ix_analysis_task_media_id'), table_name='analysis_task')
    op.drop_table('analysis_task')
    op.drop_index('ix_acl_user_time', table_name='ai_call_logs')
    op.drop_index('ix_acl_provider_model', table_name='ai_call_logs')
    op.drop_index('ix_acl_created', table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    op.drop_index('ix_ur_role', table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_ai_config_user_id'), table_name='user_ai_config')
    op.drop_table('user_ai_config')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index('ix_media_source_url', table_name='media_file', postgresql_where=sa.text('source_url IS NOT NULL'))
    op.drop_index(op.f('ix_media_file_user_id'), table_name='media_file')
    op.drop_index(op.f('ix_media_file_status'), table_name='media_file')
    op.drop_table('media_file')
    op.drop_index(op.f('ix_knowledge_base_user_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index('ux_api_key_prefix', table_name='api_key', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_index(op.f('ix_celery_task_task_name'), table_name='celery_task')
    op.drop_index(op.f('ix_celery_task_status'), table_name='celery_task')
    op.drop_table('celery_task')
    # ### end Alembic commands ###